In [2]:
import pandas as pd

In [20]:
import numpy as np

In [32]:
data = np.random.randint(0, 11, size=(4, 3))

In [34]:
data

array([[ 5,  5,  1],
       [ 4, 10,  0],
       [ 4,  3,  2],
       [ 8,  8,  7]])

In [36]:
data_frame = pd.DataFrame(data)

In [38]:
data_frame

   0   1  2
0  5   5  1
1  4  10  0
2  4   3  2
3  8   8  7

In [40]:
type(data_frame)

pandas.core.frame.DataFrame

In [42]:
type(data_frame[0])

pandas.core.series.Series

In [44]:
new_df = pd.DataFrame(data,index=["Burak","Ali","Hasan","Mehmet"],columns = ["Salary","Age","Seniority"])

In [46]:
new_df

        Salary  Age  Seniority
Burak        5    5          1
Ali          4   10          0
Hasan        4    3          2
Mehmet       8    8          7

In [50]:
new_df["Age"]

Burak      5
Ali       10
Hasan      3
Mehmet     8
Name: Age, dtype: int64

In [52]:
new_df["Salary"]

Burak     5
Ali       4
Hasan     4
Mehmet    8
Name: Salary, dtype: int64

In [54]:
new_df[["Salary","Age"]]

        Salary  Age
Burak        5    5
Ali          4   10
Hasan        4    3
Mehmet       8    8

In [58]:
new_df.loc["Burak"]

Salary       5
Age          5
Seniority    1
Name: Burak, dtype: int64

In [60]:
new_df.iloc[0]

Salary       5
Age          5
Seniority    1
Name: Burak, dtype: int64

In [62]:
new_df.iloc[1]

Salary        4
Age          10
Seniority     0
Name: Ali, dtype: int64

In [70]:
new_df.iloc[:,1]

Burak      5
Ali       10
Hasan      3
Mehmet     8
Name: Age, dtype: int64

In [104]:
new_df

        Salary  Age  Seniority
Burak        5    5          1
Ali          4   10          0
Hasan        4    3          2
Mehmet       8    8          7

In [106]:
new_df["Extra"] = 10

In [108]:
new_df

        Salary  Age  Seniority  Extra
Burak        5    5          1     10
Ali          4   10          0     10
Hasan        4    3          2     10
Mehmet       8    8          7     10

In [110]:
new_df.drop("Extra", axis = 1) # axis = 1 -> column, axis = 0 -> row // default axis = 0

        Salary  Age  Seniority
Burak        5    5          1
Ali          4   10          0
Hasan        4    3          2
Mehmet       8    8          7

In [112]:
new_df

        Salary  Age  Seniority  Extra
Burak        5    5          1     10
Ali          4   10          0     10
Hasan        4    3          2     10
Mehmet       8    8          7     10

In [114]:
new_df.drop("Extra", axis=1, inplace=True)

In [116]:
new_df

        Salary  Age  Seniority
Burak        5    5          1
Ali          4   10          0
Hasan        4    3          2
Mehmet       8    8          7

In [118]:
new_df.drop("Mehmet", axis=0)

       Salary  Age  Seniority
Burak       5    5          1
Ali         4   10          0
Hasan       4    3          2

In [120]:
new_df

        Salary  Age  Seniority
Burak        5    5          1
Ali          4   10          0
Hasan        4    3          2
Mehmet       8    8          7

In [122]:
new_df.loc["Ali"]

Salary        4
Age          10
Seniority     0
Name: Ali, dtype: int64

In [124]:
new_df.loc["Ali"]["Salary"]

4

In [126]:
new_df.loc["Burak","Salary"]

5

In [132]:
new_df.loc["Burak","Salary"] = 200

In [134]:
new_df.loc["Burak",["Salary",'Age']]

Salary    200
Age         5
Name: Burak, dtype: int64

In [136]:
new_df

        Salary  Age  Seniority
Burak      200    5          1
Ali          4   10          0
Hasan        4    3          2
Mehmet       8    8          7

In [138]:
boolean_frame = new_df > 0

In [140]:
boolean_frame

        Salary   Age  Seniority
Burak     True  True       True
Ali       True  True      False
Hasan     True  True       True
Mehmet    True  True       True

In [142]:
new_df[boolean_frame]

        Salary  Age  Seniority
Burak      200    5        1.0
Ali          4   10        NaN
Hasan        4    3        2.0
Mehmet       8    8        7.0

In [148]:
new_df[new_df > 5]

        Salary   Age  Seniority
Burak    200.0   NaN        NaN
Ali        NaN  10.0        NaN
Hasan      NaN   NaN        NaN
Mehmet     8.0   8.0        7.0

In [152]:
new_df[new_df["Salary"] > 5]

        Salary  Age  Seniority
Burak      200    5          1
Mehmet       8    8          7

In [154]:
new_df[new_df["Age"] > 5]

        Salary  Age  Seniority
Ali          4   10          0
Mehmet       8    8          7

In [156]:
new_df

        Salary  Age  Seniority
Burak      200    5          1
Ali          4   10          0
Hasan        4    3          2
Mehmet       8    8          7

In [158]:
new_df.reset_index()

    index  Salary  Age  Seniority
0   Burak     200    5          1
1     Ali       4   10          0
2   Hasan       4    3          2
3  Mehmet       8    8          7

In [160]:
new_indices = ["Brk", "Al", "Hsn", "Meh"]

In [162]:
new_df["NewIndex"] = new_indices

In [164]:
new_df

        Salary  Age  Seniority NewIndex
Burak      200    5          1      Brk
Ali          4   10          0       Al
Hasan        4    3          2      Hsn
Mehmet       8    8          7      Meh

In [166]:
new_df.set_index("NewIndex", inplace=True)

In [168]:
new_df

          Salary  Age  Seniority
NewIndex
Brk          200    5          1
Al             4   10          0
Hsn            4    3          2
Meh            8    8          7

In [170]:
new_df.loc["Brk"]

Salary       200
Age            5
Seniority      1
Name: Brk, dtype: int64

In [172]:
# multi index

In [174]:
first_index = ["Simpson","Simpson","Simpson","South Park", "South Park", "South Park"]

In [176]:
inner_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [178]:
zipped_index = list(zip(first_index, inner_index))

In [180]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [182]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [184]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [186]:
sample_values = np.ones((6,2))

In [188]:
sample_values

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [190]:
big_df = pd.DataFrame(sample_values, index=zipped_index, columns=["Age", "Salary"])

In [192]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [194]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [196]:
big_df.loc["Simpson"]

       Age  Salary
Homer  1.0     1.0
Bart   1.0     1.0
Marge  1.0     1.0

In [198]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64